steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'asia-south1-docker.pkg.dev/gcp-cloud-devops-368909/apps-repo/html-app:$SHORT_SHA'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'asia-south1-docker.pkg.dev/gcp-cloud-devops-368909/apps-repo/html-app:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  entrypoint: 'bash'
  args:
    - '-c'
    - |
         PROJECT=$$(gcloud config get-value core/project)          
         gke-gcloud-auth-plugin --version
         export USE_GKE_GCLOUD_AUTH_PLUGIN=True
         gcloud container clusters get-credentials "gke-cluster" --project "gcp-cloud-devops-368909"  --zone "asia-south1-b"  
         sed -i 's|asia-south1-docker.pkg.dev/gcp-cloud-devops-368909/apps-repo/html-app:.*|asia-south1-docker.pkg.dev/gcp-cloud-devops-368909/apps-repo/html-app:${SHORT_SHA}|' deployment.yaml 
      
         kubectl apply -f deployment.yaml

