kind: Deployment
apiVersion: apps/v1
metadata:
  name: html-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: html-app
      role: frontend
      env: production
  template:
    metadata:
      name: frontend
      labels:
        app: html-app
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: asia-south1-docker.pkg.dev/gcp-cloud-devops-368909/apps-repo/html-app:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        ports:
        - name: frontend
          containerPort: 8080
        env:
          - name: PORT
            value: "8080"
---
kind: Service
apiVersion: v1
metadata:
  name: html-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: html-app
    role: frontend
