kind: Deployment
apiVersion: apps/v1
metadata:
  name: $APP_NAME-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: $APP_NAME
      role: frontend
      env: production
  template:
    metadata:
      name: frontend
      labels:
        app: $APP_NAME
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: gcr.io/$PROJECT_ID/$APP_NAME:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        ports:
        - name: frontend
          containerPort: 8080
        env:
          - name: PORT
            value: "8080"
---
kind: Service
apiVersion: v1
metadata:
  name: $APP_NAME
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: $APP_NAME
    role: frontend
